console.log("the king said\"Begin at the beginning!\"to me");
console.log("Best");
console.log("OF LUCK");
var y;
y = 8;
y += ++y + y-- + --y;
console.log(y);
var a = 7;
a += a++ + ++a + --a + a--;
console.log(a);
var y = 10;
var z = (++y * (y++ + 5));
console.log(z);
var x = 4;
x += (x++) + (++x) + x;
console.log(x);
var k = 5;
var j = 9;
k += k++ - ++j + k;
console.log("k=" + k);
console.log("j=" + j);
console.log("Incredible" + "\n" + "world");
